# Generated by Django 5.2.8 on 2025-11-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SCHOOL_ADMIN', 'School Admin'), ('SUPER_ADMIN', 'Super Admin')], default='SCHOOL_ADMIN', max_length=20),
        ),
    ]
