# Generated by Django 5.2.8 on 2025-11-13 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='onboardmodel',
            options={'verbose_name': 'School Onboarding', 'verbose_name_plural': 'School Onboardings'},
        ),
        migrations.RenameField(
            model_name='onboardmodel',
            old_name='dateFilled',
            new_name='dateOnboarded',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
