# Generated by Django 5.2.10 on 2026-01-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
